"""Initial 3.0.0 structure.

Revision ID: f8035abd1974
Revises: 
Create Date: 2019-11-13 23:50:48.755182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8035abd1974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_hash'), ['hash'], unique=False)

    op.create_table('posts',
    sa.Column('reddit_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('subreddit', sa.String(), nullable=True),
    sa.Column('over_18', sa.Boolean(), nullable=False),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('source_alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reddit_id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('post_id', sa.String(), nullable=True),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('album_order', sa.Integer(), nullable=True),
    sa.Column('album_is_parent', sa.Boolean(), nullable=False),
    sa.Column('last_handler', sa.String(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.reddit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urls_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_failed'), ['failed'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_urls_processed'), ['processed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_processed'))
        batch_op.drop_index(batch_op.f('ix_urls_post_id'))
        batch_op.drop_index(batch_op.f('ix_urls_file_id'))
        batch_op.drop_index(batch_op.f('ix_urls_failed'))
        batch_op.drop_index(batch_op.f('ix_urls_album_id'))
        batch_op.drop_index(batch_op.f('ix_urls_address'))

    op.drop_table('urls')
    op.drop_table('posts')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_hash'))

    op.drop_table('files')
    # ### end Alembic commands ###
